### ISSUE TITLE
Build Rust starter kit

### ISSUE THREAD

**Issue by ronofays** [Lux-AI-Challenge/Lux-Design-S2#111]
Build a Rust starter kit for lux 2022.

I am learning to program Rust, and this has captivated my attention as a good project for learning.

**Comment by StoneT2000** [comment]
Looking forward to your contribution! You can use last years rust kit as inspiration, the tooling should be similar

**Comment by StoneT2000** [comment]
https://github.com/themmj/Lux-Design-2022/blob/documentation/kits/starter-kit-notes.md some nice notes from one of our engineers who works on the C++ kit

**Comment by Seamooo** [comment]
If this isn't being worked on I'd be keen to pick it up

**Comment by StoneT2000** [comment]
Yep it's not being worked on now @Seamooo feel free to make a PR. Rust is possible, there is at least 1 rust bot already on the leaderboard.
