### ISSUE TITLE
Action validation should be done within each action function.

### ISSUE THREAD

**Issue by liqimai** [Lux-AI-Challenge/Lux-Design-S2#133]
Currently, all actions are validated against the game state before any execution. However, after the execution of part of the actions, the game state changes, which makes the previous validation useless.  

A good example is that: in the initial state, the factory has enough power to build, and the build action is considered valid. However, after some robots pick up power from the factory, the factory actually does not have enough power to build, so we need to validate the build action again. This case is already specially handled in the current code, but it does **NOT** solve the problem thoroughly. 

There is another case. Assuming the factory does not have enough resources to build in its initial state, the build action is considered invalid. However, after robots transfer some resources, it has enough resources to build when the build action executes, and the build action should be considered valid. This case is not handled in the current code. 

Other examples are:
1. transfer actions affect the validity of all following actions that consume resources or power.
2. dig/destruct/movement may change rubble and thus affect the validity of factory water action.

There are too many cases to handle. **The ultra solution is to validate each action against the newest game state, not against the initial state. In short, we need to split code in `actions.validate_actions()` into `LuxAI2022._handle_*_actions()` functions.**

I am willing to make a patch if you guys do not have time to work on this.

**Comment by StoneT2000** [comment]
We'll take a look at the PR. I think there's use cases for both though but ill see.

**Comment by liqimai** [comment]
At least, the water cation should be validated against the newest game state. Otherwise, you can not cut off the strain connection by dig action. Before digging, a strain is connected, and water info is cached. After digging, the strain becomes disconnected. However, the cached water info still considers it connected, and the whole strain is watered. After watered, the dug tile will keep at least 1 lichen and still be considered connected next turn. As a result, you always cannot cut off the enemy strains' connection by digging.

**Comment by liqimai** [comment]
After pickup, water in factory cargo may decrease. Factory water may not be enough to perform water action, and will result in negative amount of water in factory cargo in current implementation.

**Comment by StoneT2000** [comment]
Actually simpler solution. We can put all transfers and pickups as the final part of turn resolution.

We generally validate against the current state as much as possible since this is easier to work with for competitors code (and easier for learning approaches since the observed values correlate directly with results)
