### ISSUE TITLE
Cpp folder isn't working correctly

### ISSUE THREAD

**Issue by Marcos-El-Flamenco** [Lux-AI-Challenge/Lux-Design-S2#139]
Hello, I am on ubuntu, and trying to get started on the competition in cpp.
I git pulled the cpp folder, and followed the readme.

When running ./compile.sh

I got an error according to which src/lux/nlohmann_json.hpp didnt exist, in fact, there is only a json.hpp file in that folder.
Apparently in the code, there are some include nlohmann_json.hpp and some include json.hpp, so i simply copied and renamed the file so i had both, when trying again thought, I got multiple pages worth of errors, according to which nothing worked anymore:

/home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/nlohmann_json.hpp:4:7: error: ‘nlohmann’ has not been declared
    4 | using nlohmann::json;
      |       ^~~~~~~~
In file included from /home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/common.hpp:4,
                 from /home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/common.cpp:1:
/home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/json.hpp:4:7: error: ‘nlohmann’ has not been declared
    4 | using nlohmann::json;
      |       ^~~~~~~~
In file included from /home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/common.cpp:1:
/home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/common.hpp:33:47: error: ‘ice’ has not been declared
   33 |     NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Cargo, ice, ore, water, metal)
      |                                               ^~~
/home/daking/luxai/Lux-Design-2022/kits/cpp/src/lux/common.hpp:33:52: error: ‘ore’ has not been declared
   33 |     NLOHMANN_DEFINE_TYPE_NON_INTRUSIVE(Cargo, ice, ore, water, metal)
      |                                                    ^~~

These are the first few error lines, after that, it's just random stuff not working, kind of like the last two lines.

Any ideas?

**Comment by StoneT2000** [comment]
@themmj

**Comment by themmj** [comment]
Hi, the `nlohmann_json.hpp` file is a dependency of the cpp kit which is downloaded when running `compile.sh`. This requires, as stated in the [readme](https://github.com/Lux-AI-Challenge/Lux-Design-2022/tree/main/kits/cpp#21-locally), `curl` to be installed. Undo your changes (renames etc.), install `curl` and try again. It should work without issues.

**Comment by themmj** [comment]
@StoneT2000 i think we can close this one. Now we even have scripts for windows that take care of those dependencies.
