### ISSUE TITLE
Pip install luxai-s2 failing when installing vec-noise

### ISSUE THREAD

**Issue by EstradaAlex20** [Lux-AI-Challenge/Lux-Design-S2#183]
I am trying to install luxai-s2, but when it gets to the vec-noise library it throws an error and fails. This is what the error looks like:

```
C:\Python39\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
  error: command 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.24.28314\bin\HostX86\x64\cl.exe' failed with exit code 2
  ----------------------------------------
  ERROR: Failed building wheel for vec-noise
```
  
  Note that i did try the solution proposed in this thread (https://stackoverflow.com/questions/53365282/cant-install-noise-module)
  
  I also tried doing pip uninstall luxai-s2 and then reinstalling and that also didn't work.
  
  Here is the full paste of the error I am getting. https://pastebin.com/akg1981t

**Comment by StoneT2000** [comment]
https://stackoverflow.com/questions/40018405/cannot-open-include-file-io-h-no-such-file-or-directory seems to work!
