### ISSUE TITLE
Issue with the RL tutorial (part 2)

### ISSUE THREAD

**Issue by LucaZanatta** [Lux-AI-Challenge/Lux-Design-S2#216]
Hi everyone, I get the following error every time I run the notebook: rl-with-lux-2-rl-problem-solving.ipynb

Process ForkServerProcess-54:
Traceback (most recent call last):
  File "/usr/lib/python3.8/multiprocessing/process.py", line 315, in _bootstrap
    self.run()
  File "/usr/lib/python3.8/multiprocessing/process.py", line 108, in run
    self._target(*self._args, **self._kwargs)
  File "~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py", line 30, in _worker
    observation, reward, done, info = env.step(data)
  File "~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/monitor.py", line 94, in step
    observation, reward, done, info = self.env.step(action)
  File "~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/gym/wrappers/time_limit.py", line 18, in step
    observation, reward, done, info = self.env.step(action)
  File "/tmp/ipykernel_1949576/2513648194.py", line 25, in step
TypeError: 'bool' object is not subscriptable

---------------------------------------------------------------------------
EOFError                                  Traceback (most recent call last)
Cell In[14], line 2
      1 total_timesteps = 10_000_000
----> 2 model.learn(
      3     total_timesteps,
      4     callback=[TensorboardCallback(tag="train_metrics"), eval_callback],
      5 )
      6 model.save(osp.join(log_path, "models/latest_model"))

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/ppo/ppo.py:307, in PPO.learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps, progress_bar)
    297 def learn(
    298     self: SelfPPO,
    299     total_timesteps: int,
   (...)
    304     progress_bar: bool = False,
    305 ) -> SelfPPO:
--> 307     return super().learn(
    308         total_timesteps=total_timesteps,
    309         callback=callback,
    310         log_interval=log_interval,
    311         tb_log_name=tb_log_name,
    312         reset_num_timesteps=reset_num_timesteps,
    313         progress_bar=progress_bar,
    314     )

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py:248, in OnPolicyAlgorithm.learn(self, total_timesteps, callback, log_interval, tb_log_name, reset_num_timesteps, progress_bar)
    244 callback.on_training_start(locals(), globals())
    246 while self.num_timesteps < total_timesteps:
--> 248     continue_training = self.collect_rollouts(self.env, callback, self.rollout_buffer, n_rollout_steps=self.n_steps)
    250     if continue_training is False:
    251         break

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/on_policy_algorithm.py:181, in OnPolicyAlgorithm.collect_rollouts(self, env, callback, rollout_buffer, n_rollout_steps)
    179 # Give access to local variables
    180 callback.update_locals(locals())
--> 181 if callback.on_step() is False:
    182     return False
    184 self._update_info_buffer(infos)

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:100, in BaseCallback.on_step(self)
     97 self.n_calls += 1
     98 self.num_timesteps = self.model.num_timesteps
--> 100 return self._on_step()

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:204, in CallbackList._on_step(self)
    201 continue_training = True
    202 for callback in self.callbacks:
    203     # Return False (stop training) if at least one callback returns False
--> 204     continue_training = callback.on_step() and continue_training
    205 return continue_training

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:100, in BaseCallback.on_step(self)
     97 self.n_calls += 1
     98 self.num_timesteps = self.model.num_timesteps
--> 100 return self._on_step()

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/callbacks.py:447, in EvalCallback._on_step(self)
    444 # Reset success rate buffer
    445 self._is_success_buffer = []
--> 447 episode_rewards, episode_lengths = evaluate_policy(
    448     self.model,
    449     self.eval_env,
    450     n_eval_episodes=self.n_eval_episodes,
    451     render=self.render,
    452     deterministic=self.deterministic,
    453     return_episode_rewards=True,
    454     warn=self.warn,
    455     callback=self._log_success_callback,
    456 )
    458 if self.log_path is not None:
    459     self.evaluations_timesteps.append(self.num_timesteps)

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/evaluation.py:89, in evaluate_policy(model, env, n_eval_episodes, deterministic, render, callback, reward_threshold, return_episode_rewards, warn)
     87 while (episode_counts < episode_count_targets).any():
     88     actions, states = model.predict(observations, state=states, episode_start=episode_starts, deterministic=deterministic)
---> 89     observations, rewards, dones, infos = env.step(actions)
     90     current_rewards += rewards
     91     current_lengths += 1

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/base_vec_env.py:163, in VecEnv.step(self, actions)
    156 """
    157 Step the environments with the given action
    158 
    159 :param actions: the action
    160 :return: observation, reward, done, information
    161 """
    162 self.step_async(actions)
--> 163 return self.step_wait()

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py:121, in SubprocVecEnv.step_wait(self)
    120 def step_wait(self) -> VecEnvStepReturn:
--> 121     results = [remote.recv() for remote in self.remotes]
    122     self.waiting = False
    123     obs, rews, dones, infos = zip(*results)

File ~/didattica/varie/luxai2023v2/env/lib/python3.8/site-packages/stable_baselines3/common/vec_env/subproc_vec_env.py:121, in <listcomp>(.0)
    120 def step_wait(self) -> VecEnvStepReturn:
--> 121     results = [remote.recv() for remote in self.remotes]
    122     self.waiting = False
    123     obs, rews, dones, infos = zip(*results)

File /usr/lib/python3.8/multiprocessing/connection.py:250, in _ConnectionBase.recv(self)
    248 self._check_closed()
    249 self._check_readable()
--> 250 buf = self._recv_bytes()
    251 return _ForkingPickler.loads(buf.getbuffer())

File /usr/lib/python3.8/multiprocessing/connection.py:414, in Connection._recv_bytes(self, maxsize)
    413 def _recv_bytes(self, maxsize=None):
--> 414     buf = self._recv(4)
    415     size, = struct.unpack("!i", buf.getvalue())
    416     if size == -1:

File /usr/lib/python3.8/multiprocessing/connection.py:383, in Connection._recv(self, size, read)
    381 if n == 0:
    382     if remaining == size:
--> 383         raise EOFError
    384     else:
    385         raise OSError("got end of file during message")

EOFError:

**Comment by StoneT2000** [comment]
please use the latest version of the lux ai package

**Comment by LucaZanatta** [comment]
Great! Thanks.
