### ISSUE TITLE
Feature Request: upgrade from gym to gymnasium

### ISSUE THREAD

**Issue by elliottower** [Lux-AI-Challenge/Lux-Design-S2#229]
Hi, sorry if this is the wrong place to ask this, but I was wondering if it would be possible for the next Lux Design challenge (S3) to use gymnasium rather than gym? We would like to list this challenge in this list of  [third party environments](https://gymnasium.farama.org/environments/third_party_environments/), but are only adding environments which use gymnasium.
  
[Gymnasium](https://github.com/Farama-Foundation/Gymnasium) a maintained fork of openai gym and is designed as a drop-in replacement (`import gym` -> `import gymnasium as gym`). Beyond just bugfixes, many RL training libraries have also switched ([rllib](https://github.com/ray-project/ray/tree/master/rllib), [tianshou](https://github.com/thu-ml/tianshou), [CleanRL](https://github.com/vwxyzjn/cleanrl)), or are planning to switch ([stable-baselines3](https://github.com/DLR-RM/stable-baselines3/blob/e5deeed16efb57c34ccdcb14692439154d970527/docs/guide/install.rst#bleeding-edge-version)). It would be great if users could train agents on Habitat using the latest models and features from these libraries (e.g., scalable distributed training/model serving using [Ray](https://github.com/ray-project/ray)/[RLlib](https://github.com/ray-project/ray/tree/master/rllib)). 

For information about upgrading and compatibility, see [migration guide](https://gymnasium.farama.org/content/migration-guide/) and [gym compatibility](https://gymnasium.farama.org/content/gym_compatibility/). The main difference is the API has switched to returning `truncated` and `terminated`, rather than `done`, in order to give more information and mitigate edge case issues (for example, many popular tutorials/implementations of Q learning using gym were actually incorrect because of `done`, there will be an upcoming blog post explaining more details about this on the Farama site (https://farama.org/blog).

**Comment by StoneT2000** [comment]
Yes we plan to migrate to gymnasium by season 3 minimum (and probably any other competition after season 2).

**Comment by StoneT2000** [comment]
This is finally complete @elliottower. Closed by #232

**Comment by elliottower** [comment]
Amazing to hear, cheers!

**Comment by elliottower** [comment]
I’d like to add this to our list of third party environments, would you like to provide a concise description or tagline? If you’d like to do a PR for it feel free otherwise we can.

https://gymnasium.farama.org/environments/third_party_environments/

**Comment by StoneT2000** [comment]
will make a PR later, thanks

**Comment by StoneT2000** [comment]
Does this work @elliottower 

```
Lux AI Challenge Season 2 is a large-scale multi-agent game where two teams control hundreds of unit in a complex resource management game. The goal is to terraform mars more than the opponent. This environment was used as a competition on Kaggle for NeurIPS'23 https://www.kaggle.com/competitions/lux-ai-season-2-neurips-stage-2, and comes with an equivalent GPU optimized jax implementation.
```

**Comment by elliottower** [comment]
That should be good, thanks!

**Comment by elliottower** [comment]
FYI it looks like there’s still some files like environment.yml that say gym v21 and older versions of pettingzoo, it may be worth specifying at least pettingzoo>=1.22 as that is when it was updated to use gymnasium instead of relying on gym. 

Current version is 1.24, it and 1.23 have had large amounts of bugfixes but sometimes researchers need to use specific versions for compatibility with training libraries etc, so probably best to do as loose a requirement as possible, while still using the gymnasium compatible API (>=1.22)

**Comment by StoneT2000** [comment]
Oh need to delete that file. The setup code for the actual environment is in the luxai_s2 folder (which uses a simpler setup.py).

**Comment by elliottower** [comment]
Sounds good, just fyi pyproject.toml makes installation more consistent for all systems and virtual environments and is the modern python PEP standard, if you’re changing things for the new season you could switch to that as well
