### ISSUE TITLE
gym==0.21.0 is deprecated

### ISSUE THREAD

**Issue by liqimai** [Lux-AI-Challenge/Lux-Design-S2#233]
The current required version of gym is 0.21.0, which is already deprecated and will result in errors while installed by the latest pip. Please take a look at the following example for more info.
- https://github.com/openai/gym/issues/3176#issuecomment-1408598628
- https://github.com/freqtrade/freqtrade/issues/8376#issuecomment-1520844382

Please consider updating the gym requirement to a newer version.

**Comment by StoneT2000** [comment]
closed by #232
