### ISSUE TITLE
Update JS kits with new constants, and updated API

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-S2#52]
New API removes `can_x` functions as submitting an action queue incurs power as well so it could be confusing.

Moreover, default random agent should check move_cost is not null and move_cost + action_queue_cost <= unit.power

**Comment by themmj** [comment]
C++ kit done with #53

**Comment by themmj** [comment]
The JS kit is so bare-bones that there is no adjustment necessary. So this issue itself is done.
If you want to, I can get the JS kit to feature parity with the other kits (e.g. `factory_occupancy_map`, convenience functions to create actions etc.)
