### ISSUE TITLE
Create env State from an observation and guide for how to create a LuxAI2022 Env and perform rollouts

### ISSUE THREAD

**Issue by StoneT2000** [Lux-AI-Challenge/Lux-Design-S2#73]

**Comment by harmbuisman** [comment]
+1

I guess this is about implementing this?:
```
    def from_obs(obs):
        # generate state from compressed obs
        pass
```

**Comment by StoneT2000** [comment]
Yep its that, there's a bit of extra work though since the observation currently doesn't include some information (like global_id which is used to generate unit ids)

**Comment by StoneT2000** [comment]
Another feature request related to this. In starter kits, provide an option in main.py to provide stacked future observation frames where they execute remaining actions for `k` turns.

**Comment by StoneT2000** [comment]
part 1 done by #170
